
#define EMERGENCY_NAME_LENGTH 64
#define RESCUER_NAME_LENGTH 64
#define LINE_LENGTH 1024


#define BASSA_PRIOR 0
#define MEDIA_PRIOR 1
#define ALTA_PRIOR 2

#define MEDIA_PRIOR_TIME 30 
#define ALTA_PRIOR_TIME 10

