#Configurazione Server

server.port=8080
server.address=127.0.0.1
server.saveinterval=1
#server.saveinterval=5
server.datapath=data
server.wordspath=data/words.json
server.timer=40
#server.timer=300
#indicato in secondi
