#Configurazione Server

server.port=8080
server.address=127.0.0.1
server.persistence.interval.minutes=5
server.words.dataset.path=data/words.json
server.data.dir=data
server.timer.seconds=300
#server.timer.seconds=300
